spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tpmall
    url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
    username: tpmall

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log

