/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : 127.0.0.1
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : TPMALL

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2020-10-14 14:45:26
*/


-- ----------------------------
-- Table structure for CONFIG_ACCESS_KEY
-- ----------------------------
DROP TABLE "CONFIG_ACCESS_KEY";
CREATE TABLE "CONFIG_ACCESS_KEY" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"ENABLED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"SECRET" VARCHAR2(128 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_ACCESS_KEY
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_APP
-- ----------------------------
DROP TABLE "CONFIG_APP";
CREATE TABLE "CONFIG_APP" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"NAME" VARCHAR2(500 BYTE) NOT NULL ,
"ORG_ID" VARCHAR2(32 BYTE) NOT NULL ,
"ORG_NAME" VARCHAR2(64 BYTE) NOT NULL ,
"OWNER_EMAIL" VARCHAR2(500 BYTE) NOT NULL ,
"OWNER_NAME" VARCHAR2(500 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_APP
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_APP_NAMESPACE
-- ----------------------------
DROP TABLE "CONFIG_APP_NAMESPACE";
CREATE TABLE "CONFIG_APP_NAMESPACE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(32 BYTE) NOT NULL ,
"COMMENT_MSG" VARCHAR2(1024 BYTE) NULL ,
"FORMAT" VARCHAR2(32 BYTE) NOT NULL ,
"PUBLIC_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAME" VARCHAR2(32 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_APP_NAMESPACE
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_AUDIT
-- ----------------------------
DROP TABLE "CONFIG_AUDIT";
CREATE TABLE "CONFIG_AUDIT" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"COMMENT_MSG" VARCHAR2(500 BYTE) NULL ,
"ENTITY_ID" NUMBER(19) NULL ,
"ENTITY_NAME" VARCHAR2(500 BYTE) NOT NULL ,
"OP_NAME" VARCHAR2(50 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_AUDIT
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_CLUSTER
-- ----------------------------
DROP TABLE "CONFIG_CLUSTER";
CREATE TABLE "CONFIG_CLUSTER" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"NAME" VARCHAR2(32 BYTE) NOT NULL ,
"PARENT_CLUSTER_ID" NUMBER(19) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_CLUSTER
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_COMMIT
-- ----------------------------
DROP TABLE "CONFIG_COMMIT";
CREATE TABLE "CONFIG_COMMIT" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"CHANGE_SETS" CLOB NOT NULL ,
"CLUSTER_NAME" VARCHAR2(500 BYTE) NOT NULL ,
"COMMENT_MSG" VARCHAR2(500 BYTE) NULL ,
"NAMESPACE_NAME" VARCHAR2(500 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_COMMIT
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_GRAY_RELEASE_RULE
-- ----------------------------
DROP TABLE "CONFIG_GRAY_RELEASE_RULE";
CREATE TABLE "CONFIG_GRAY_RELEASE_RULE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"BRANCH_NAME" VARCHAR2(32 BYTE) NOT NULL ,
"BRANCH_STATUS" NUMBER(10) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(32 BYTE) NOT NULL ,
"NAMESPACE_NAME" VARCHAR2(32 BYTE) NOT NULL ,
"RELEASE_ID" NUMBER(19) NOT NULL ,
"RULES" LONG NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_GRAY_RELEASE_RULE
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_INSTANCE
-- ----------------------------
DROP TABLE "CONFIG_INSTANCE";
CREATE TABLE "CONFIG_INSTANCE" (
"ID" NUMBER(19) NOT NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(32 BYTE) NOT NULL ,
"DATA_CENTER" VARCHAR2(64 BYTE) NOT NULL ,
"DATACHANGE_CREATEDTIME" DATE NOT NULL ,
"DATACHANGE_LASTTIME" DATE NULL ,
"IP" VARCHAR2(32 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_INSTANCE
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_INSTANCE_CONFIG
-- ----------------------------
DROP TABLE "CONFIG_INSTANCE_CONFIG";
CREATE TABLE "CONFIG_INSTANCE_CONFIG" (
"ID" NUMBER(19) NOT NULL ,
"CONFIG_APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_NAMESPACE_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"DATACHANGE_CREATEDTIME" DATE NOT NULL ,
"DATACHANGE_LASTTIME" DATE NULL ,
"INSTANCE_ID" NUMBER(19) NULL ,
"RELEASE_DELIVERY_TIME" DATE NULL ,
"RELEASE_KEY" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_INSTANCE_CONFIG
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_ITEM
-- ----------------------------
DROP TABLE "CONFIG_ITEM";
CREATE TABLE "CONFIG_ITEM" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"COMMENT_MSG" VARCHAR2(1024 BYTE) NULL ,
"ITEM_KEY" VARCHAR2(255 BYTE) NOT NULL ,
"LINE_NUM" NUMBER(10) NULL ,
"NAMESPACE_ID" NUMBER(19) NOT NULL ,
"ITEM_VALUE" CLOB NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_ITEM
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_NAMESPACE
-- ----------------------------
DROP TABLE "CONFIG_NAMESPACE";
CREATE TABLE "CONFIG_NAMESPACE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(500 BYTE) NOT NULL ,
"NAMESPACE_NAME" VARCHAR2(500 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_NAMESPACE
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_NAMESPACE_LOCK
-- ----------------------------
DROP TABLE "CONFIG_NAMESPACE_LOCK";
CREATE TABLE "CONFIG_NAMESPACE_LOCK" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAMESPACE_ID" NUMBER(19) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_NAMESPACE_LOCK
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_PRIVILEGE
-- ----------------------------
DROP TABLE "CONFIG_PRIVILEGE";
CREATE TABLE "CONFIG_PRIVILEGE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"NAMESPACE_ID" NUMBER(19) NULL ,
"PRIVIL_TYPE" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_PRIVILEGE
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_RELEASE
-- ----------------------------
DROP TABLE "CONFIG_RELEASE";
CREATE TABLE "CONFIG_RELEASE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(500 BYTE) NOT NULL ,
"COMMENT_MSG" VARCHAR2(500 BYTE) NULL ,
"CONFIGURATIONS" CLOB NOT NULL ,
"ABANDONED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"NAMESPACE_NAME" VARCHAR2(500 BYTE) NOT NULL ,
"RELEASE_KEY" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_RELEASE
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_RELEASE_HISTORY
-- ----------------------------
DROP TABLE "CONFIG_RELEASE_HISTORY";
CREATE TABLE "CONFIG_RELEASE_HISTORY" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"BRANCH_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"NAMESPACE_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"OPERATION" NUMBER(10) NOT NULL ,
"OPERATION_CONTEXT" VARCHAR2(255 BYTE) NOT NULL ,
"PREVIOUS_RELEASE_ID" NUMBER(19) NOT NULL ,
"RELEASE_ID" NUMBER(19) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_RELEASE_HISTORY
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_RELEASE_MESSAGE
-- ----------------------------
DROP TABLE "CONFIG_RELEASE_MESSAGE";
CREATE TABLE "CONFIG_RELEASE_MESSAGE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_LASTTIME" DATE NULL ,
"MESSAGE" VARCHAR2(1024 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_RELEASE_MESSAGE
-- ----------------------------

-- ----------------------------
-- Table structure for CONFIG_SERVER_CONFIG
-- ----------------------------
DROP TABLE "CONFIG_SERVER_CONFIG";
CREATE TABLE "CONFIG_SERVER_CONFIG" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CLUSTER_ADDRESS" VARCHAR2(32 BYTE) NOT NULL ,
"CONFIG_COMMENT" VARCHAR2(1024 BYTE) NULL ,
"CONFIG_KEY" VARCHAR2(64 BYTE) NOT NULL ,
"CONFIG_VALUE" VARCHAR2(2048 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONFIG_SERVER_CONFIG
-- ----------------------------
INSERT INTO "CONFIG_SERVER_CONFIG" VALUES ('1', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:419000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:419000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', 'Eureka服务Url，多个service以英文逗号分隔', 'eureka.service.url', 'http://localhost:8080/eureka/');
INSERT INTO "CONFIG_SERVER_CONFIG" VALUES ('2', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:623000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:623000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', '一次发布只能有一个人修改开关', 'namespace.lock.switch', 'false');
INSERT INTO "CONFIG_SERVER_CONFIG" VALUES ('3', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:625000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:625000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', 'item key 最大长度限制', 'item.key.length.limit', '128');
INSERT INTO "CONFIG_SERVER_CONFIG" VALUES ('4', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:627000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:627000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', 'item value最大长度限制', 'item.value.length.limit', '20000');
INSERT INTO "CONFIG_SERVER_CONFIG" VALUES ('5', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:629000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:59:629000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！', 'config-service.cache.enabled', 'false');

-- ----------------------------
-- Table structure for PORTAL_APP
-- ----------------------------
DROP TABLE "PORTAL_APP";
CREATE TABLE "PORTAL_APP" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"NAME" VARCHAR2(500 BYTE) NOT NULL ,
"ORG_ID" VARCHAR2(32 BYTE) NOT NULL ,
"ORG_NAME" VARCHAR2(64 BYTE) NOT NULL ,
"OWNER_EMAIL" VARCHAR2(500 BYTE) NOT NULL ,
"OWNER_NAME" VARCHAR2(500 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_APP
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_APP_NAMESPACE
-- ----------------------------
DROP TABLE "PORTAL_APP_NAMESPACE";
CREATE TABLE "PORTAL_APP_NAMESPACE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(32 BYTE) NOT NULL ,
"COMMENT_MSG" VARCHAR2(1024 BYTE) NULL ,
"FORMAT" VARCHAR2(32 BYTE) NOT NULL ,
"PUBLIC_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAME" VARCHAR2(32 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_APP_NAMESPACE
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_AUTHORITIES
-- ----------------------------
DROP TABLE "PORTAL_AUTHORITIES";
CREATE TABLE "PORTAL_AUTHORITIES" (
"ID" NUMBER(19) NOT NULL ,
"AUTHORITY" VARCHAR2(50 BYTE) NOT NULL ,
"USERNAME" VARCHAR2(64 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_AUTHORITIES
-- ----------------------------
INSERT INTO "PORTAL_AUTHORITIES" VALUES ('4', 'ROLE_user', 'apollo');

-- ----------------------------
-- Table structure for PORTAL_CONSUMER
-- ----------------------------
DROP TABLE "PORTAL_CONSUMER";
CREATE TABLE "PORTAL_CONSUMER" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"NAME" VARCHAR2(500 BYTE) NOT NULL ,
"ORG_ID" VARCHAR2(32 BYTE) NOT NULL ,
"ORG_NAME" VARCHAR2(64 BYTE) NOT NULL ,
"OWNER_EMAIL" VARCHAR2(500 BYTE) NOT NULL ,
"OWNER_NAME" VARCHAR2(500 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_CONSUMER
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_CONSUMER_AUDIT
-- ----------------------------
DROP TABLE "PORTAL_CONSUMER_AUDIT";
CREATE TABLE "PORTAL_CONSUMER_AUDIT" (
"ID" NUMBER(19) NOT NULL ,
"CONSUMER_ID" NUMBER(19) NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"METHOD" VARCHAR2(16 BYTE) NOT NULL ,
"URI" VARCHAR2(1024 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_CONSUMER_AUDIT
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_CONSUMER_ROLE
-- ----------------------------
DROP TABLE "PORTAL_CONSUMER_ROLE";
CREATE TABLE "PORTAL_CONSUMER_ROLE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CONSUMER_ID" NUMBER(19) NULL ,
"ROLE_ID" NUMBER(19) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_CONSUMER_ROLE
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_CONSUMER_TOKEN
-- ----------------------------
DROP TABLE "PORTAL_CONSUMER_TOKEN";
CREATE TABLE "PORTAL_CONSUMER_TOKEN" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CONSUMER_ID" NUMBER(19) NULL ,
"EXPIRES" DATE NOT NULL ,
"TOKEN" VARCHAR2(128 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_CONSUMER_TOKEN
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_FAVORITE
-- ----------------------------
DROP TABLE "PORTAL_FAVORITE";
CREATE TABLE "PORTAL_FAVORITE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(500 BYTE) NOT NULL ,
"POSITION" NUMBER(19) NOT NULL ,
"USER_ID" VARCHAR2(32 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_FAVORITE
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_PERMISSION
-- ----------------------------
DROP TABLE "PORTAL_PERMISSION";
CREATE TABLE "PORTAL_PERMISSION" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"PERMISSION_TYPE" VARCHAR2(32 BYTE) NOT NULL ,
"TARGET_ID" VARCHAR2(256 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_PERMISSION
-- ----------------------------
INSERT INTO "PORTAL_PERMISSION" VALUES ('1', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:11:884000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:11:884000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'CreateApplication', 'SystemRole');

-- ----------------------------
-- Table structure for PORTAL_ROLE
-- ----------------------------
DROP TABLE "PORTAL_ROLE";
CREATE TABLE "PORTAL_ROLE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"ROLE_NAME" VARCHAR2(256 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_ROLE
-- ----------------------------
INSERT INTO "PORTAL_ROLE" VALUES ('2', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:11:901000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:11:901000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'CreateApplication+SystemRole');

-- ----------------------------
-- Table structure for PORTAL_ROLE_PERMISSION
-- ----------------------------
DROP TABLE "PORTAL_ROLE_PERMISSION";
CREATE TABLE "PORTAL_ROLE_PERMISSION" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"PERMISSION_ID" NUMBER(19) NULL ,
"ROLE_ID" NUMBER(19) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_ROLE_PERMISSION
-- ----------------------------
INSERT INTO "PORTAL_ROLE_PERMISSION" VALUES ('3', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:11:903000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:11:903000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '1', '2');

-- ----------------------------
-- Table structure for PORTAL_SERVER_CONFIG
-- ----------------------------
DROP TABLE "PORTAL_SERVER_CONFIG";
CREATE TABLE "PORTAL_SERVER_CONFIG" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CONFIG_COMMENT" VARCHAR2(1024 BYTE) NULL ,
"CONFIG_KEY" VARCHAR2(256 BYTE) NOT NULL ,
"CONFIG_VALUE" VARCHAR2(2048 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_SERVER_CONFIG
-- ----------------------------
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('5', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:640000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:640000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '可支持的环境列表', 'apollo.portal.envs', 'dev,sit,uat');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('6', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:819000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:819000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '部门列表', 'organizations', '[{"orgId":"TPIS-00057","orgName":"应用系统三部"}]');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('7', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:824000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:824000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'Portal超级管理员', 'superAdmin', 'apollo');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('8', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:829000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:829000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'http接口read timeout', 'api.readTimeout', '10000');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('9', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:833000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:833000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'consumer token salt', 'consumer.token.salt', 'someSalt');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('10', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:837000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:837000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '是否允许项目管理员创建私有namespace', 'admin.createPrivateNamespace.switch', 'true');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('11', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:842000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:842000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '只对项目成员显示配置信息的环境列表，多个env以英文逗号分隔', 'configView.memberOnly.envs', 'pro');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('12', 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:847000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-14 14:41:12:847000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '各环境Meta Service列表', 'apollo.portal.meta.servers', '{}');

-- ----------------------------
-- Table structure for PORTAL_USER_ROLE
-- ----------------------------
DROP TABLE "PORTAL_USER_ROLE";
CREATE TABLE "PORTAL_USER_ROLE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"ROLE_ID" NUMBER(19) NULL ,
"USER_ID" VARCHAR2(128 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_USER_ROLE
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_USERS
-- ----------------------------
DROP TABLE "PORTAL_USERS";
CREATE TABLE "PORTAL_USERS" (
"ID" NUMBER(19) NOT NULL ,
"EMAIL" VARCHAR2(64 BYTE) NOT NULL ,
"ENABLED" NUMBER(10) NULL ,
"PASSWORD" VARCHAR2(64 BYTE) NOT NULL ,
"USERNAME" VARCHAR2(64 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_USERS
-- ----------------------------
INSERT INTO "PORTAL_USERS" VALUES ('13', 'apollo@acme.com', '1', '$2a$10$7r20uS.BQ9uBpf3Baj3uQOZvMVvB1RN3PYoKE94gtz2.WAOuiiwXS', 'apollo');

-- ----------------------------
-- Sequence structure for APOLLO_ID_SEQ
-- ----------------------------
DROP SEQUENCE "APOLLO_ID_SEQ";
CREATE SEQUENCE "APOLLO_ID_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_BASE_JOB_INFO
-- ----------------------------
DROP SEQUENCE "APOLLO_ITEM_ID_SEQ";
CREATE SEQUENCE "APOLLO_ITEM_ID_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999
 START WITH 101
 CACHE 50
 CYCLE ;

-- ----------------------------
-- Indexes structure for table CONFIG_ACCESS_KEY
-- ----------------------------
CREATE INDEX "IDX_ACCESS_KEY_APP_ID"
ON "CONFIG_ACCESS_KEY" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ACCKEY_CHANGE_LASTTIME"
ON "CONFIG_ACCESS_KEY" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_ACCESS_KEY
-- ----------------------------
ALTER TABLE "CONFIG_ACCESS_KEY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_ACCESS_KEY" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_ACCESS_KEY" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_ACCESS_KEY" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_ACCESS_KEY" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_ACCESS_KEY" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_ACCESS_KEY" ADD CHECK ("SECRET" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_ACCESS_KEY
-- ----------------------------
ALTER TABLE "CONFIG_ACCESS_KEY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_APP
-- ----------------------------
CREATE INDEX "IDX_APP_APP_ID"
ON "CONFIG_APP" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_APP_DATACHANGE_LASTTIME"
ON "CONFIG_APP" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_APP_NAME"
ON "CONFIG_APP" ("NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_APP
-- ----------------------------
ALTER TABLE "CONFIG_APP" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("ORG_ID" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("ORG_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("OWNER_EMAIL" IS NOT NULL);
ALTER TABLE "CONFIG_APP" ADD CHECK ("OWNER_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_APP
-- ----------------------------
ALTER TABLE "CONFIG_APP" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_APP_NAMESPACE
-- ----------------------------
CREATE INDEX "IDX_APPNASP_CHANGE_LASTTIME"
ON "CONFIG_APP_NAMESPACE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_APP_NAMESPACE_APP_ID"
ON "CONFIG_APP_NAMESPACE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_APP_NAMESPACE_NAME"
ON "CONFIG_APP_NAMESPACE" ("NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_APP_NAMESPACE
-- ----------------------------
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD CHECK ("FORMAT" IS NOT NULL);
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD CHECK ("NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_APP_NAMESPACE
-- ----------------------------
ALTER TABLE "CONFIG_APP_NAMESPACE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_AUDIT
-- ----------------------------
CREATE INDEX "IDX_AUDIT_DATACHANGE_LASTTIME"
ON "CONFIG_AUDIT" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_AUDIT
-- ----------------------------
ALTER TABLE "CONFIG_AUDIT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_AUDIT" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_AUDIT" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_AUDIT" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_AUDIT" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_AUDIT" ADD CHECK ("ENTITY_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_AUDIT" ADD CHECK ("OP_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_AUDIT
-- ----------------------------
ALTER TABLE "CONFIG_AUDIT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_CLUSTER
-- ----------------------------
CREATE INDEX "IDX_CLUSTER_APP_ID"
ON "CONFIG_CLUSTER" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CLUSTER_CHANGE_LASTTIME"
ON "CONFIG_CLUSTER" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CLUSTER_NAME"
ON "CONFIG_CLUSTER" ("NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CLUSTER_PARENT_ID"
ON "CONFIG_CLUSTER" ("PARENT_CLUSTER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_CLUSTER
-- ----------------------------
ALTER TABLE "CONFIG_CLUSTER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_CLUSTER" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_CLUSTER" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_CLUSTER" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_CLUSTER" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_CLUSTER" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_CLUSTER" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "CONFIG_CLUSTER" ADD CHECK ("PARENT_CLUSTER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_CLUSTER
-- ----------------------------
ALTER TABLE "CONFIG_CLUSTER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_COMMIT
-- ----------------------------
CREATE INDEX "IDX_COMMIT_APP_ID"
ON "CONFIG_COMMIT" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_COMMIT_CHANGE_LASTTIME"
ON "CONFIG_COMMIT" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_COMMIT_CLUSTER_NAME"
ON "CONFIG_COMMIT" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_COMMIT_NAMESPACE_NAME"
ON "CONFIG_COMMIT" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_COMMIT
-- ----------------------------
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("CHANGE_SETS" IS NOT NULL);
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_COMMIT" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_COMMIT
-- ----------------------------
ALTER TABLE "CONFIG_COMMIT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_GRAY_RELEASE_RULE
-- ----------------------------
CREATE INDEX "IDX_GRARRULE_APP_ID"
ON "CONFIG_GRAY_RELEASE_RULE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_GRARRULE_CHANGE_LASTTIME"
ON "CONFIG_GRAY_RELEASE_RULE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_GRARRULE_CLUSTER_NAME"
ON "CONFIG_GRAY_RELEASE_RULE" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_GRARRULE_NAMESPACE_NAME"
ON "CONFIG_GRAY_RELEASE_RULE" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_GRARRULE_RELEASE_ID"
ON "CONFIG_GRAY_RELEASE_RULE" ("RELEASE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_GRAY_RELEASE_RULE
-- ----------------------------
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("BRANCH_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("BRANCH_STATUS" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD CHECK ("RELEASE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_GRAY_RELEASE_RULE
-- ----------------------------
ALTER TABLE "CONFIG_GRAY_RELEASE_RULE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_INSTANCE
-- ----------------------------
CREATE INDEX "IDX_INSTANCE_CHANGE_LASTTIME"
ON "CONFIG_INSTANCE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSTANCE_IP"
ON "CONFIG_INSTANCE" ("IP" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Uniques structure for table CONFIG_INSTANCE
-- ----------------------------
ALTER TABLE "CONFIG_INSTANCE" ADD UNIQUE ("APP_ID", "CLUSTER_NAME", "DATA_CENTER", "IP");

-- ----------------------------
-- Checks structure for table CONFIG_INSTANCE
-- ----------------------------
ALTER TABLE "CONFIG_INSTANCE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE" ADD CHECK ("DATA_CENTER" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE" ADD CHECK ("IP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_INSTANCE
-- ----------------------------
ALTER TABLE "CONFIG_INSTANCE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_INSTANCE_CONFIG
-- ----------------------------
CREATE INDEX "IDX_INSCONFIG_CHANGE_LASTTIME"
ON "CONFIG_INSTANCE_CONFIG" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSCONFIG_CLUSTER_NAME"
ON "CONFIG_INSTANCE_CONFIG" ("CONFIG_CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSCONFIG_CONFIG_APP_ID"
ON "CONFIG_INSTANCE_CONFIG" ("CONFIG_APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSCONFIG_NAMESPACE_NAME"
ON "CONFIG_INSTANCE_CONFIG" ("CONFIG_NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSCONFIG_RELEASE_KEY"
ON "CONFIG_INSTANCE_CONFIG" ("RELEASE_KEY" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Uniques structure for table CONFIG_INSTANCE_CONFIG
-- ----------------------------
ALTER TABLE "CONFIG_INSTANCE_CONFIG" ADD UNIQUE ("INSTANCE_ID", "CONFIG_APP_ID", "CONFIG_NAMESPACE_NAME");

-- ----------------------------
-- Checks structure for table CONFIG_INSTANCE_CONFIG
-- ----------------------------
ALTER TABLE "CONFIG_INSTANCE_CONFIG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE_CONFIG" ADD CHECK ("CONFIG_APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE_CONFIG" ADD CHECK ("CONFIG_CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE_CONFIG" ADD CHECK ("CONFIG_NAMESPACE_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE_CONFIG" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_INSTANCE_CONFIG" ADD CHECK ("RELEASE_KEY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_INSTANCE_CONFIG
-- ----------------------------
ALTER TABLE "CONFIG_INSTANCE_CONFIG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_ITEM
-- ----------------------------
CREATE INDEX "IDX_ITEM_CHANGE_LASTTIME"
ON "CONFIG_ITEM" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ITEM_NAMESPACE_ID"
ON "CONFIG_ITEM" ("NAMESPACE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_ITEM
-- ----------------------------
ALTER TABLE "CONFIG_ITEM" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_ITEM" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_ITEM" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_ITEM" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_ITEM" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_ITEM" ADD CHECK ("ITEM_KEY" IS NOT NULL);
ALTER TABLE "CONFIG_ITEM" ADD CHECK ("NAMESPACE_ID" IS NOT NULL);
ALTER TABLE "CONFIG_ITEM" ADD CHECK ("ITEM_VALUE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_ITEM
-- ----------------------------
ALTER TABLE "CONFIG_ITEM" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_NAMESPACE
-- ----------------------------
CREATE INDEX "IDX_NAMESPACE_APP_ID"
ON "CONFIG_NAMESPACE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_NAMESPACE_CHANGE_LASTTIME"
ON "CONFIG_NAMESPACE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_NAMESPACE_CLUSTER_NAME"
ON "CONFIG_NAMESPACE" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_NAMESPACE_NAMESPACE_NAME"
ON "CONFIG_NAMESPACE" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_NAMESPACE
-- ----------------------------
ALTER TABLE "CONFIG_NAMESPACE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_NAMESPACE
-- ----------------------------
ALTER TABLE "CONFIG_NAMESPACE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_NAMESPACE_LOCK
-- ----------------------------
CREATE INDEX "IDX_NAMESPLOCK_CHANGE_LASTTIME"
ON "CONFIG_NAMESPACE_LOCK" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Uniques structure for table CONFIG_NAMESPACE_LOCK
-- ----------------------------
ALTER TABLE "CONFIG_NAMESPACE_LOCK" ADD UNIQUE ("NAMESPACE_ID");

-- ----------------------------
-- Checks structure for table CONFIG_NAMESPACE_LOCK
-- ----------------------------
ALTER TABLE "CONFIG_NAMESPACE_LOCK" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE_LOCK" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE_LOCK" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE_LOCK" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE_LOCK" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_NAMESPACE_LOCK" ADD CHECK ("NAMESPACE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_NAMESPACE_LOCK
-- ----------------------------
ALTER TABLE "CONFIG_NAMESPACE_LOCK" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_PRIVILEGE
-- ----------------------------
CREATE INDEX "IDX_PRIVILEGE_CHANGE_LASTTIME"
ON "CONFIG_PRIVILEGE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_PRIVILEGE_NAMESPACE_ID"
ON "CONFIG_PRIVILEGE" ("NAMESPACE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_PRIVILEGE
-- ----------------------------
ALTER TABLE "CONFIG_PRIVILEGE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_PRIVILEGE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_PRIVILEGE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_PRIVILEGE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_PRIVILEGE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_PRIVILEGE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "CONFIG_PRIVILEGE" ADD CHECK ("PRIVIL_TYPE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_PRIVILEGE
-- ----------------------------
ALTER TABLE "CONFIG_PRIVILEGE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_RELEASE
-- ----------------------------
CREATE INDEX "IDX_RELEASE_APP_ID"
ON "CONFIG_RELEASE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASE_CHANGE_LASTTIME"
ON "CONFIG_RELEASE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASE_CLUSTER_NAME"
ON "CONFIG_RELEASE" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASE_NAMESPACE_NAME"
ON "CONFIG_RELEASE" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASE_RELEASE_KEY"
ON "CONFIG_RELEASE" ("RELEASE_KEY" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_RELEASE
-- ----------------------------
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("CONFIGURATIONS" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE" ADD CHECK ("RELEASE_KEY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_RELEASE
-- ----------------------------
ALTER TABLE "CONFIG_RELEASE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_RELEASE_HISTORY
-- ----------------------------
CREATE INDEX "IDX_RELEASEHI_APP_ID"
ON "CONFIG_RELEASE_HISTORY" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_BRANCH_NAME"
ON "CONFIG_RELEASE_HISTORY" ("BRANCH_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_CHANGE_LASTTIME"
ON "CONFIG_RELEASE_HISTORY" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_CLUSTER_NAME"
ON "CONFIG_RELEASE_HISTORY" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_NAMESPACE_NAME"
ON "CONFIG_RELEASE_HISTORY" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_RELEASE_ID"
ON "CONFIG_RELEASE_HISTORY" ("RELEASE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_RELEASE_HISTORY
-- ----------------------------
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("BRANCH_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("OPERATION" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("OPERATION_CONTEXT" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("PREVIOUS_RELEASE_ID" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD CHECK ("RELEASE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_RELEASE_HISTORY
-- ----------------------------
ALTER TABLE "CONFIG_RELEASE_HISTORY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_RELEASE_MESSAGE
-- ----------------------------
CREATE INDEX "IDX_RELEASEMES_CHANGE_LASTTIME"
ON "CONFIG_RELEASE_MESSAGE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEMES_MESSAGE"
ON "CONFIG_RELEASE_MESSAGE" ("MESSAGE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_RELEASE_MESSAGE
-- ----------------------------
ALTER TABLE "CONFIG_RELEASE_MESSAGE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_RELEASE_MESSAGE" ADD CHECK ("MESSAGE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_RELEASE_MESSAGE
-- ----------------------------
ALTER TABLE "CONFIG_RELEASE_MESSAGE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONFIG_SERVER_CONFIG
-- ----------------------------
CREATE INDEX "IDX_SERCONFIG_CHANGE_LASTTIME"
ON "CONFIG_SERVER_CONFIG" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_SERCONFIG_CONFIG_KEY"
ON "CONFIG_SERVER_CONFIG" ("CONFIG_KEY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_SERCONFIG_CONFIG_VALUE"
ON "CONFIG_SERVER_CONFIG" ("CONFIG_VALUE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONFIG_SERVER_CONFIG
-- ----------------------------
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD CHECK ("CLUSTER_ADDRESS" IS NOT NULL);
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD CHECK ("CONFIG_KEY" IS NOT NULL);
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD CHECK ("CONFIG_VALUE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONFIG_SERVER_CONFIG
-- ----------------------------
ALTER TABLE "CONFIG_SERVER_CONFIG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_APP
-- ----------------------------
CREATE INDEX "IDX_POAPP_APP_ID"
ON "PORTAL_APP" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POAPP_DATACHANGE_LASTTIME"
ON "PORTAL_APP" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POAPP_NAME"
ON "PORTAL_APP" ("NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_APP
-- ----------------------------
ALTER TABLE "PORTAL_APP" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("ORG_ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("ORG_NAME" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("OWNER_EMAIL" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("OWNER_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_APP
-- ----------------------------
ALTER TABLE "PORTAL_APP" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_APP_NAMESPACE
-- ----------------------------
CREATE INDEX "IDX_POAPPNASP_CHANGE_LASTTIME"
ON "PORTAL_APP_NAMESPACE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POAPP_NAMESPACE_APP_ID"
ON "PORTAL_APP_NAMESPACE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POAPP_NAMESPACE_NAME"
ON "PORTAL_APP_NAMESPACE" ("NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_APP_NAMESPACE
-- ----------------------------
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("FORMAT" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_APP_NAMESPACE
-- ----------------------------
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_AUTHORITIES
-- ----------------------------

-- ----------------------------
-- Checks structure for table PORTAL_AUTHORITIES
-- ----------------------------
ALTER TABLE "PORTAL_AUTHORITIES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_AUTHORITIES" ADD CHECK ("AUTHORITY" IS NOT NULL);
ALTER TABLE "PORTAL_AUTHORITIES" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_AUTHORITIES
-- ----------------------------
ALTER TABLE "PORTAL_AUTHORITIES" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_CONSUMER
-- ----------------------------
CREATE INDEX "IDX_CONSUMER_APP_ID"
ON "PORTAL_CONSUMER" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONSUMER_CHANGE_LASTTIME"
ON "PORTAL_CONSUMER" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_CONSUMER
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("ORG_ID" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("ORG_NAME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("OWNER_EMAIL" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER" ADD CHECK ("OWNER_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_CONSUMER
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_CONSUMER_AUDIT
-- ----------------------------
CREATE INDEX "IDX_CONAUDIT_CHANGE_LASTTIME"
ON "PORTAL_CONSUMER_AUDIT" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONAUDIT_CONSUMER_ID"
ON "PORTAL_CONSUMER_AUDIT" ("CONSUMER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_CONSUMER_AUDIT
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER_AUDIT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_AUDIT" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_AUDIT" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_AUDIT" ADD CHECK ("METHOD" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_AUDIT" ADD CHECK ("URI" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_CONSUMER_AUDIT
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER_AUDIT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_CONSUMER_ROLE
-- ----------------------------
CREATE INDEX "IDX_CONROLE_CHANGE_LASTTIME"
ON "PORTAL_CONSUMER_ROLE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONROLE_CONSUMER_ID"
ON "PORTAL_CONSUMER_ROLE" ("CONSUMER_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONROLE_ROLE_ID"
ON "PORTAL_CONSUMER_ROLE" ("ROLE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_CONSUMER_ROLE
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_ROLE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_ROLE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_ROLE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_ROLE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_CONSUMER_ROLE
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_CONSUMER_TOKEN
-- ----------------------------
CREATE INDEX "IDX_CONTOKEN_CHANGE_LASTTIME"
ON "PORTAL_CONSUMER_TOKEN" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONTOKEN_CONSUMER_ID"
ON "PORTAL_CONSUMER_TOKEN" ("CONSUMER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Uniques structure for table PORTAL_CONSUMER_TOKEN
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD UNIQUE ("TOKEN");

-- ----------------------------
-- Checks structure for table PORTAL_CONSUMER_TOKEN
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD CHECK ("EXPIRES" IS NOT NULL);
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD CHECK ("TOKEN" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_CONSUMER_TOKEN
-- ----------------------------
ALTER TABLE "PORTAL_CONSUMER_TOKEN" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_FAVORITE
-- ----------------------------
CREATE INDEX "IDX_FAVORITE_APP_ID"
ON "PORTAL_FAVORITE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_FAVORITE_CHANGE_LASTTIME"
ON "PORTAL_FAVORITE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_FAVORITE_USER_ID"
ON "PORTAL_FAVORITE" ("USER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_FAVORITE
-- ----------------------------
ALTER TABLE "PORTAL_FAVORITE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_FAVORITE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_FAVORITE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_FAVORITE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_FAVORITE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_FAVORITE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "PORTAL_FAVORITE" ADD CHECK ("POSITION" IS NOT NULL);
ALTER TABLE "PORTAL_FAVORITE" ADD CHECK ("USER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_FAVORITE
-- ----------------------------
ALTER TABLE "PORTAL_FAVORITE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_PERMISSION
-- ----------------------------
CREATE INDEX "IDX_PERM_CHANGE_LASTTIME"
ON "PORTAL_PERMISSION" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_PERM_PERMISSION_TYPE"
ON "PORTAL_PERMISSION" ("PERMISSION_TYPE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_PERM_TARGET_ID"
ON "PORTAL_PERMISSION" ("TARGET_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_PERMISSION
-- ----------------------------
ALTER TABLE "PORTAL_PERMISSION" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_PERMISSION" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_PERMISSION" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_PERMISSION" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_PERMISSION" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_PERMISSION" ADD CHECK ("PERMISSION_TYPE" IS NOT NULL);
ALTER TABLE "PORTAL_PERMISSION" ADD CHECK ("TARGET_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_PERMISSION
-- ----------------------------
ALTER TABLE "PORTAL_PERMISSION" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_ROLE
-- ----------------------------
CREATE INDEX "IDX_ROLE_CHANGE_LASTTIME"
ON "PORTAL_ROLE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ROLE_ROLE_NAME"
ON "PORTAL_ROLE" ("ROLE_NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_ROLE
-- ----------------------------
ALTER TABLE "PORTAL_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE" ADD CHECK ("ROLE_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_ROLE
-- ----------------------------
ALTER TABLE "PORTAL_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_ROLE_PERMISSION
-- ----------------------------
CREATE INDEX "IDX_ROLEPERM_CHANGE_LASTTIME"
ON "PORTAL_ROLE_PERMISSION" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ROLEPERM_PERMISSION_ID"
ON "PORTAL_ROLE_PERMISSION" ("PERMISSION_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ROLEPERM_ROLE_ID"
ON "PORTAL_ROLE_PERMISSION" ("ROLE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "PORTAL_ROLE_PERMISSION" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE_PERMISSION" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE_PERMISSION" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE_PERMISSION" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_ROLE_PERMISSION" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "PORTAL_ROLE_PERMISSION" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_SERVER_CONFIG
-- ----------------------------
CREATE INDEX "IDX_POSERCONFIG_CHALASTTIME"
ON "PORTAL_SERVER_CONFIG" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POSERCONFIG_CONFIG_KEY"
ON "PORTAL_SERVER_CONFIG" ("CONFIG_KEY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POSERCONFIG_CONFIG_VALUE"
ON "PORTAL_SERVER_CONFIG" ("CONFIG_VALUE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_SERVER_CONFIG
-- ----------------------------
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("CONFIG_KEY" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("CONFIG_VALUE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_SERVER_CONFIG
-- ----------------------------
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_USER_ROLE
-- ----------------------------
CREATE INDEX "IDX_USERROLE_CHANGE_LASTTIME"
ON "PORTAL_USER_ROLE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_USERROLE_ROLE_ID"
ON "PORTAL_USER_ROLE" ("ROLE_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_USERROLE_USER_ID"
ON "PORTAL_USER_ROLE" ("USER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_USER_ROLE
-- ----------------------------
ALTER TABLE "PORTAL_USER_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_USER_ROLE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_USER_ROLE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_USER_ROLE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_USER_ROLE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_USER_ROLE
-- ----------------------------
ALTER TABLE "PORTAL_USER_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_USERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table PORTAL_USERS
-- ----------------------------
ALTER TABLE "PORTAL_USERS" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_USERS" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "PORTAL_USERS" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "PORTAL_USERS" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_USERS
-- ----------------------------
ALTER TABLE "PORTAL_USERS" ADD PRIMARY KEY ("ID");
