/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : 127.0.0.1
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : TPMALL

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2020-10-13 11:13:58
*/


-- ----------------------------
-- Table structure for ACCESS_KEY
-- ----------------------------
DROP TABLE "ACCESS_KEY";
CREATE TABLE "ACCESS_KEY" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"ENABLED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"SECRET" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ACCESS_KEY
-- ----------------------------

-- ----------------------------
-- Table structure for APOLLO_AUDIT
-- ----------------------------
DROP TABLE "APOLLO_AUDIT";
CREATE TABLE "APOLLO_AUDIT" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"COMMENT_MSG" VARCHAR2(255 BYTE) NULL ,
"ENTITY_ID" NUMBER(19) NULL ,
"ENTITY_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"OP_NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of APOLLO_AUDIT
-- ----------------------------

-- ----------------------------
-- Table structure for APOLLO_CLUSTER
-- ----------------------------
DROP TABLE "APOLLO_CLUSTER";
CREATE TABLE "APOLLO_CLUSTER" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"PARENT_CLUSTER_ID" NUMBER(19) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of APOLLO_CLUSTER
-- ----------------------------

-- ----------------------------
-- Table structure for APOLLO_COMMIT
-- ----------------------------
DROP TABLE "APOLLO_COMMIT";
CREATE TABLE "APOLLO_COMMIT" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"CHANGE_SETS" CLOB NOT NULL ,
"CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"COMMENT_MSG" VARCHAR2(255 BYTE) NULL ,
"NAMESPACE_NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of APOLLO_COMMIT
-- ----------------------------

-- ----------------------------
-- Table structure for APP
-- ----------------------------
DROP TABLE "APP";
CREATE TABLE "APP" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"ORG_ID" VARCHAR2(255 BYTE) NOT NULL ,
"ORG_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"OWNER_EMAIL" VARCHAR2(255 BYTE) NOT NULL ,
"OWNER_NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of APP
-- ----------------------------

-- ----------------------------
-- Table structure for APP_NAMESPACE
-- ----------------------------
DROP TABLE "APP_NAMESPACE";
CREATE TABLE "APP_NAMESPACE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"COMMENT_MSG" VARCHAR2(255 BYTE) NULL ,
"FORMAT" VARCHAR2(255 BYTE) NOT NULL ,
"PUBLIC_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of APP_NAMESPACE
-- ----------------------------

-- ----------------------------
-- Table structure for AUTHORITIES
-- ----------------------------
DROP TABLE "AUTHORITIES";
CREATE TABLE "AUTHORITIES" (
"ID" NUMBER(19) NOT NULL ,
"AUTHORITY" VARCHAR2(255 BYTE) NOT NULL ,
"USERNAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of AUTHORITIES
-- ----------------------------
INSERT INTO "AUTHORITIES" VALUES ('13', 'ROLE_user', 'apollo');

-- ----------------------------
-- Table structure for CONSUMER
-- ----------------------------
DROP TABLE "CONSUMER";
CREATE TABLE "CONSUMER" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"ORG_ID" VARCHAR2(255 BYTE) NOT NULL ,
"ORG_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"OWNER_EMAIL" VARCHAR2(255 BYTE) NOT NULL ,
"OWNER_NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONSUMER
-- ----------------------------

-- ----------------------------
-- Table structure for CONSUMER_AUDIT
-- ----------------------------
DROP TABLE "CONSUMER_AUDIT";
CREATE TABLE "CONSUMER_AUDIT" (
"ID" NUMBER(19) NOT NULL ,
"CONSUMER_ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"METHOD" VARCHAR2(255 BYTE) NOT NULL ,
"URI" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONSUMER_AUDIT
-- ----------------------------

-- ----------------------------
-- Table structure for CONSUMER_ROLE
-- ----------------------------
DROP TABLE "CONSUMER_ROLE";
CREATE TABLE "CONSUMER_ROLE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CONSUMER_ID" NUMBER(19) NOT NULL ,
"ROLE_ID" NUMBER(19) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONSUMER_ROLE
-- ----------------------------

-- ----------------------------
-- Table structure for CONSUMER_TOKEN
-- ----------------------------
DROP TABLE "CONSUMER_TOKEN";
CREATE TABLE "CONSUMER_TOKEN" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CONSUMER_ID" NUMBER(19) NOT NULL ,
"EXPIRES" DATE NOT NULL ,
"TOKEN" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of CONSUMER_TOKEN
-- ----------------------------

-- ----------------------------
-- Table structure for FAVORITE
-- ----------------------------
DROP TABLE "FAVORITE";
CREATE TABLE "FAVORITE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"POSITION" NUMBER(19) NULL ,
"USER_ID" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of FAVORITE
-- ----------------------------

-- ----------------------------
-- Table structure for GRAY_RELEASE_RULE
-- ----------------------------
DROP TABLE "GRAY_RELEASE_RULE";
CREATE TABLE "GRAY_RELEASE_RULE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"BRANCH_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"BRANCH_STATUS" NUMBER(10) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"NAMESPACE_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"RELEASE_ID" NUMBER(19) NOT NULL ,
"RULES" VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of GRAY_RELEASE_RULE
-- ----------------------------

-- ----------------------------
-- Table structure for INSTANCE
-- ----------------------------
DROP TABLE "INSTANCE";
CREATE TABLE "INSTANCE" (
"ID" NUMBER(19) NOT NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"DATA_CENTER" VARCHAR2(255 BYTE) NOT NULL ,
"DATACHANGE_CREATEDTIME" DATE NOT NULL ,
"DATACHANGE_LASTTIME" DATE NULL ,
"IP" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of INSTANCE
-- ----------------------------

-- ----------------------------
-- Table structure for INSTANCE_CONFIG
-- ----------------------------
DROP TABLE "INSTANCE_CONFIG";
CREATE TABLE "INSTANCE_CONFIG" (
"ID" NUMBER(19) NOT NULL ,
"CONFIG_APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_NAMESPACE_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"DATACHANGE_CREATEDTIME" DATE NOT NULL ,
"DATACHANGE_LASTTIME" DATE NULL ,
"INSTANCE_ID" NUMBER(19) NULL ,
"RELEASE_DELIVERY_TIME" DATE NOT NULL ,
"RELEASE_KEY" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of INSTANCE_CONFIG
-- ----------------------------

-- ----------------------------
-- Table structure for ITEM
-- ----------------------------
DROP TABLE "ITEM";
CREATE TABLE "ITEM" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"COMMENT_MSG" VARCHAR2(255 BYTE) NULL ,
"ITEM_KEY" VARCHAR2(255 BYTE) NOT NULL ,
"LINE_NUM" NUMBER(10) NULL ,
"NAMESPACE_ID" NUMBER(19) NOT NULL ,
"ITEM_VALUE" CLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ITEM
-- ----------------------------

-- ----------------------------
-- Table structure for NAMESPACE
-- ----------------------------
DROP TABLE "NAMESPACE";
CREATE TABLE "NAMESPACE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"NAMESPACE_NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of NAMESPACE
-- ----------------------------

-- ----------------------------
-- Table structure for NAMESPACE_LOCK
-- ----------------------------
DROP TABLE "NAMESPACE_LOCK";
CREATE TABLE "NAMESPACE_LOCK" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAMESPACE_ID" NUMBER(19) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of NAMESPACE_LOCK
-- ----------------------------

-- ----------------------------
-- Table structure for PERMISSION
-- ----------------------------
DROP TABLE "PERMISSION";
CREATE TABLE "PERMISSION" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"PERMISSION_TYPE" VARCHAR2(255 BYTE) NOT NULL ,
"TARGET_ID" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PERMISSION
-- ----------------------------
INSERT INTO "PERMISSION" VALUES ('1', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:26:444000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:26:444000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'CreateApplication', 'SystemRole');

-- ----------------------------
-- Table structure for PORTAL_APP
-- ----------------------------
DROP TABLE "PORTAL_APP";
CREATE TABLE "PORTAL_APP" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"ORG_ID" VARCHAR2(255 BYTE) NOT NULL ,
"ORG_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"OWNER_EMAIL" VARCHAR2(255 BYTE) NOT NULL ,
"OWNER_NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_APP
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_APP_NAMESPACE
-- ----------------------------
DROP TABLE "PORTAL_APP_NAMESPACE";
CREATE TABLE "PORTAL_APP_NAMESPACE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"COMMENT_MSG" VARCHAR2(255 BYTE) NULL ,
"FORMAT" VARCHAR2(255 BYTE) NOT NULL ,
"PUBLIC_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_APP_NAMESPACE
-- ----------------------------

-- ----------------------------
-- Table structure for PORTAL_SERVER_CONFIG
-- ----------------------------
DROP TABLE "PORTAL_SERVER_CONFIG";
CREATE TABLE "PORTAL_SERVER_CONFIG" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CONFIG_COMMENT" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_KEY" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_VALUE" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PORTAL_SERVER_CONFIG
-- ----------------------------
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('4', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:046000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:046000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '可支持的环境列表', 'apollo.portal.envs', 'dev');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('5', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:201000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:201000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '部门列表', 'organizations', '[{"orgId":"TEST1","orgName":"样例部门1"},{"orgId":"TEST2","orgName":"样例部门2"}]');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('6', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:205000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:205000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'Portal超级管理员', 'superAdmin', 'apollo');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('7', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:209000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:209000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'http接口read timeout', 'api.readTimeout', '10000');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('8', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:214000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:214000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'consumer token salt', 'consumer.token.salt', 'someSalt');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('9', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:217000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:217000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '是否允许项目管理员创建私有namespace', 'admin.createPrivateNamespace.switch', 'true');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('10', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:221000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:221000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '只对项目成员显示配置信息的环境列表，多个env以英文逗号分隔', 'configView.memberOnly.envs', 'pro');
INSERT INTO "PORTAL_SERVER_CONFIG" VALUES ('11', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:239000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:27:239000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '各环境Meta Service列表', 'apollo.portal.meta.servers', '{}');

-- ----------------------------
-- Table structure for PRIVILEGE
-- ----------------------------
DROP TABLE "PRIVILEGE";
CREATE TABLE "PRIVILEGE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"NAMESPACE_ID" NUMBER(19) NULL ,
"PRIVIL_TYPE" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of PRIVILEGE
-- ----------------------------

-- ----------------------------
-- Table structure for RELEASE
-- ----------------------------
DROP TABLE "RELEASE";
CREATE TABLE "RELEASE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"COMMENT_MSG" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIGURATIONS" CLOB NOT NULL ,
"ABANDONED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"NAME" VARCHAR2(255 BYTE) NOT NULL ,
"NAMESPACE_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"RELEASE_KEY" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of RELEASE
-- ----------------------------

-- ----------------------------
-- Table structure for RELEASE_HISTORY
-- ----------------------------
DROP TABLE "RELEASE_HISTORY";
CREATE TABLE "RELEASE_HISTORY" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"APP_ID" VARCHAR2(255 BYTE) NOT NULL ,
"BRANCH_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"CLUSTER_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"NAMESPACE_NAME" VARCHAR2(255 BYTE) NOT NULL ,
"OPERATION" NUMBER(10) NULL ,
"OPERATION_CONTEXT" VARCHAR2(255 BYTE) NOT NULL ,
"PREVIOUS_RELEASE_ID" NUMBER(19) NULL ,
"RELEASE_ID" NUMBER(19) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of RELEASE_HISTORY
-- ----------------------------

-- ----------------------------
-- Table structure for RELEASE_MESSAGE
-- ----------------------------
DROP TABLE "RELEASE_MESSAGE";
CREATE TABLE "RELEASE_MESSAGE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_LASTTIME" DATE NULL ,
"MESSAGE" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of RELEASE_MESSAGE
-- ----------------------------

-- ----------------------------
-- Table structure for ROLE
-- ----------------------------
DROP TABLE "ROLE";
CREATE TABLE "ROLE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"ROLE_NAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ROLE
-- ----------------------------
INSERT INTO "ROLE" VALUES ('2', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:26:461000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:26:461000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'CreateApplication+SystemRole');

-- ----------------------------
-- Table structure for ROLE_PERMISSION
-- ----------------------------
DROP TABLE "ROLE_PERMISSION";
CREATE TABLE "ROLE_PERMISSION" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"PERMISSION_ID" NUMBER(19) NOT NULL ,
"ROLE_ID" NUMBER(19) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of ROLE_PERMISSION
-- ----------------------------
INSERT INTO "ROLE_PERMISSION" VALUES ('3', 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:26:463000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 10:35:26:463000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', '1', '2');

-- ----------------------------
-- Table structure for SERVER_CONFIG
-- ----------------------------
DROP TABLE "SERVER_CONFIG";
CREATE TABLE "SERVER_CONFIG" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"CLUSTER_ADDRESS" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_COMMENT" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_KEY" VARCHAR2(255 BYTE) NOT NULL ,
"CONFIG_VALUE" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of SERVER_CONFIG
-- ----------------------------
INSERT INTO "SERVER_CONFIG" VALUES ('1', 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:699000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:699000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', 'Eureka服务Url，多个service以英文逗号分隔', 'eureka.service.url', 'http://localhost:8080/eureka/');
INSERT INTO "SERVER_CONFIG" VALUES ('2', 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:802000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:802000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', '一次发布只能有一个人修改开关', 'namespace.lock.switch', 'false');
INSERT INTO "SERVER_CONFIG" VALUES ('3', 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:805000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:805000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', 'item key 最大长度限制', 'item.key.length.limit', '128');
INSERT INTO "SERVER_CONFIG" VALUES ('4', 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:807000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:807000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', 'item value最大长度限制', 'item.value.length.limit', '20000');
INSERT INTO "SERVER_CONFIG" VALUES ('5', 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:810000', 'YYYY-MM-DD HH24:MI:SS:FF6'), 'apollo', TO_TIMESTAMP(' 2020-10-13 11:12:45:810000', 'YYYY-MM-DD HH24:MI:SS:FF6'), '0', 'default', 'ConfigService是否开启缓存，开启后能提高性能，但是会增大内存消耗！', 'config-service.cache.enabled', 'false');

-- ----------------------------
-- Table structure for USER_ROLE
-- ----------------------------
DROP TABLE "USER_ROLE";
CREATE TABLE "USER_ROLE" (
"ID" NUMBER(19) NOT NULL ,
"DATACHANGE_CREATEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_CREATEDTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DATACHANGE_LASTMODIFIEDBY" VARCHAR2(255 BYTE) DEFAULT 'apollo'  NOT NULL ,
"DATACHANGE_LASTTIME" TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP  NOT NULL ,
"DELETED_FLAG" NUMBER(1) DEFAULT 0  NULL ,
"ROLE_ID" NUMBER(19) NOT NULL ,
"USER_ID" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of USER_ROLE
-- ----------------------------

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "USERS";
CREATE TABLE "USERS" (
"ID" NUMBER(19) NOT NULL ,
"EMAIL" VARCHAR2(255 BYTE) NOT NULL ,
"ENABLED" NUMBER(10) NOT NULL ,
"PASSWORD" VARCHAR2(255 BYTE) NOT NULL ,
"USERNAME" VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "USERS" VALUES ('12', 'apollo@acme.com', '1', '$2a$10$7r20uS.BQ9uBpf3Baj3uQOZvMVvB1RN3PYoKE94gtz2.WAOuiiwXS', 'apollo');

-- ----------------------------
-- Sequence structure for APOLLO_ID_SEQ
-- ----------------------------
DROP SEQUENCE "APOLLO_ID_SEQ";
CREATE SEQUENCE "APOLLO_ID_SEQ"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 21
 CACHE 20;

-- ----------------------------
-- Sequence structure for SEQ_BASE_JOB_INFO
-- ----------------------------
DROP SEQUENCE "SEQ_BASE_JOB_INFO";
CREATE SEQUENCE "SEQ_BASE_JOB_INFO"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999
 START WITH 101
 CACHE 50
 CYCLE ;

-- ----------------------------
-- Indexes structure for table ACCESS_KEY
-- ----------------------------
CREATE INDEX "IDX_ACCESS_KEY_APP_ID"
ON "ACCESS_KEY" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ACCKEY_CHANGE_LASTTIME"
ON "ACCESS_KEY" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ACCESS_KEY
-- ----------------------------
ALTER TABLE "ACCESS_KEY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "ACCESS_KEY" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "ACCESS_KEY" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "ACCESS_KEY" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "ACCESS_KEY" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "ACCESS_KEY" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "ACCESS_KEY" ADD CHECK ("SECRET" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ACCESS_KEY
-- ----------------------------
ALTER TABLE "ACCESS_KEY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table APOLLO_AUDIT
-- ----------------------------
CREATE INDEX "IDX_AUDIT_DATACHANGE_LASTTIME"
ON "APOLLO_AUDIT" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table APOLLO_AUDIT
-- ----------------------------
ALTER TABLE "APOLLO_AUDIT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "APOLLO_AUDIT" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "APOLLO_AUDIT" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "APOLLO_AUDIT" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "APOLLO_AUDIT" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "APOLLO_AUDIT" ADD CHECK ("ENTITY_NAME" IS NOT NULL);
ALTER TABLE "APOLLO_AUDIT" ADD CHECK ("OP_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table APOLLO_AUDIT
-- ----------------------------
ALTER TABLE "APOLLO_AUDIT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table APOLLO_CLUSTER
-- ----------------------------
CREATE INDEX "IDX_CLUSTER_APP_ID"
ON "APOLLO_CLUSTER" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CLUSTER_CHANGE_LASTTIME"
ON "APOLLO_CLUSTER" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CLUSTER_NAME"
ON "APOLLO_CLUSTER" ("NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CLUSTER_PARENT_ID"
ON "APOLLO_CLUSTER" ("PARENT_CLUSTER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table APOLLO_CLUSTER
-- ----------------------------
ALTER TABLE "APOLLO_CLUSTER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "APOLLO_CLUSTER" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "APOLLO_CLUSTER" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "APOLLO_CLUSTER" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "APOLLO_CLUSTER" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "APOLLO_CLUSTER" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "APOLLO_CLUSTER" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "APOLLO_CLUSTER" ADD CHECK ("PARENT_CLUSTER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table APOLLO_CLUSTER
-- ----------------------------
ALTER TABLE "APOLLO_CLUSTER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table APOLLO_COMMIT
-- ----------------------------
CREATE INDEX "IDX_COMMIT_APP_ID"
ON "APOLLO_COMMIT" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_COMMIT_CHANGE_LASTTIME"
ON "APOLLO_COMMIT" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_COMMIT_CLUSTER_NAME"
ON "APOLLO_COMMIT" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_COMMIT_NAMESPACE_NAME"
ON "APOLLO_COMMIT" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table APOLLO_COMMIT
-- ----------------------------
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("CHANGE_SETS" IS NOT NULL);
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "APOLLO_COMMIT" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table APOLLO_COMMIT
-- ----------------------------
ALTER TABLE "APOLLO_COMMIT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table APP
-- ----------------------------
CREATE INDEX "IDX_APP_APP_ID"
ON "APP" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_APP_DATACHANGE_LASTTIME"
ON "APP" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_APP_NAME"
ON "APP" ("NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table APP
-- ----------------------------
ALTER TABLE "APP" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("ORG_ID" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("ORG_NAME" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("OWNER_EMAIL" IS NOT NULL);
ALTER TABLE "APP" ADD CHECK ("OWNER_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table APP
-- ----------------------------
ALTER TABLE "APP" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table APP_NAMESPACE
-- ----------------------------
CREATE INDEX "IDX_APPNASP_CHANGE_LASTTIME"
ON "APP_NAMESPACE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_APP_NAMESPACE_APP_ID"
ON "APP_NAMESPACE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_APP_NAMESPACE_NAME"
ON "APP_NAMESPACE" ("NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table APP_NAMESPACE
-- ----------------------------
ALTER TABLE "APP_NAMESPACE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "APP_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "APP_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "APP_NAMESPACE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "APP_NAMESPACE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "APP_NAMESPACE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "APP_NAMESPACE" ADD CHECK ("FORMAT" IS NOT NULL);
ALTER TABLE "APP_NAMESPACE" ADD CHECK ("NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table APP_NAMESPACE
-- ----------------------------
ALTER TABLE "APP_NAMESPACE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table AUTHORITIES
-- ----------------------------

-- ----------------------------
-- Checks structure for table AUTHORITIES
-- ----------------------------
ALTER TABLE "AUTHORITIES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "AUTHORITIES" ADD CHECK ("AUTHORITY" IS NOT NULL);
ALTER TABLE "AUTHORITIES" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table AUTHORITIES
-- ----------------------------
ALTER TABLE "AUTHORITIES" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONSUMER
-- ----------------------------
CREATE INDEX "IDX_CONSUMER_APP_ID"
ON "CONSUMER" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONSUMER_CHANGE_LASTTIME"
ON "CONSUMER" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONSUMER
-- ----------------------------
ALTER TABLE "CONSUMER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("ORG_ID" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("ORG_NAME" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("OWNER_EMAIL" IS NOT NULL);
ALTER TABLE "CONSUMER" ADD CHECK ("OWNER_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONSUMER
-- ----------------------------
ALTER TABLE "CONSUMER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONSUMER_AUDIT
-- ----------------------------
CREATE INDEX "IDX_CONAUDIT_CHANGE_LASTTIME"
ON "CONSUMER_AUDIT" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONAUDIT_CONSUMER_ID"
ON "CONSUMER_AUDIT" ("CONSUMER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONSUMER_AUDIT
-- ----------------------------
ALTER TABLE "CONSUMER_AUDIT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONSUMER_AUDIT" ADD CHECK ("CONSUMER_ID" IS NOT NULL);
ALTER TABLE "CONSUMER_AUDIT" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONSUMER_AUDIT" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONSUMER_AUDIT" ADD CHECK ("METHOD" IS NOT NULL);
ALTER TABLE "CONSUMER_AUDIT" ADD CHECK ("URI" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONSUMER_AUDIT
-- ----------------------------
ALTER TABLE "CONSUMER_AUDIT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONSUMER_ROLE
-- ----------------------------
CREATE INDEX "IDX_CONROLE_CHANGE_LASTTIME"
ON "CONSUMER_ROLE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONROLE_CONSUMER_ID"
ON "CONSUMER_ROLE" ("CONSUMER_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONROLE_ROLE_ID"
ON "CONSUMER_ROLE" ("ROLE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table CONSUMER_ROLE
-- ----------------------------
ALTER TABLE "CONSUMER_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONSUMER_ROLE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONSUMER_ROLE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONSUMER_ROLE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONSUMER_ROLE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONSUMER_ROLE" ADD CHECK ("CONSUMER_ID" IS NOT NULL);
ALTER TABLE "CONSUMER_ROLE" ADD CHECK ("ROLE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONSUMER_ROLE
-- ----------------------------
ALTER TABLE "CONSUMER_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table CONSUMER_TOKEN
-- ----------------------------
CREATE INDEX "IDX_CONTOKEN_CHANGE_LASTTIME"
ON "CONSUMER_TOKEN" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_CONTOKEN_CONSUMER_ID"
ON "CONSUMER_TOKEN" ("CONSUMER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Uniques structure for table CONSUMER_TOKEN
-- ----------------------------
ALTER TABLE "CONSUMER_TOKEN" ADD UNIQUE ("TOKEN");

-- ----------------------------
-- Checks structure for table CONSUMER_TOKEN
-- ----------------------------
ALTER TABLE "CONSUMER_TOKEN" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "CONSUMER_TOKEN" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "CONSUMER_TOKEN" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "CONSUMER_TOKEN" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "CONSUMER_TOKEN" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "CONSUMER_TOKEN" ADD CHECK ("CONSUMER_ID" IS NOT NULL);
ALTER TABLE "CONSUMER_TOKEN" ADD CHECK ("EXPIRES" IS NOT NULL);
ALTER TABLE "CONSUMER_TOKEN" ADD CHECK ("TOKEN" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CONSUMER_TOKEN
-- ----------------------------
ALTER TABLE "CONSUMER_TOKEN" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FAVORITE
-- ----------------------------
CREATE INDEX "IDX_FAVORITE_APP_ID"
ON "FAVORITE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_FAVORITE_CHANGE_LASTTIME"
ON "FAVORITE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_FAVORITE_USER_ID"
ON "FAVORITE" ("USER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table FAVORITE
-- ----------------------------
ALTER TABLE "FAVORITE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FAVORITE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "FAVORITE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "FAVORITE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "FAVORITE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "FAVORITE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "FAVORITE" ADD CHECK ("USER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FAVORITE
-- ----------------------------
ALTER TABLE "FAVORITE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table GRAY_RELEASE_RULE
-- ----------------------------
CREATE INDEX "IDX_GRARRULE_APP_ID"
ON "GRAY_RELEASE_RULE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_GRARRULE_CHANGE_LASTTIME"
ON "GRAY_RELEASE_RULE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_GRARRULE_CLUSTER_NAME"
ON "GRAY_RELEASE_RULE" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_GRARRULE_NAMESPACE_NAME"
ON "GRAY_RELEASE_RULE" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_GRARRULE_RELEASE_ID"
ON "GRAY_RELEASE_RULE" ("RELEASE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table GRAY_RELEASE_RULE
-- ----------------------------
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("BRANCH_NAME" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("BRANCH_STATUS" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);
ALTER TABLE "GRAY_RELEASE_RULE" ADD CHECK ("RELEASE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table GRAY_RELEASE_RULE
-- ----------------------------
ALTER TABLE "GRAY_RELEASE_RULE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table INSTANCE
-- ----------------------------
CREATE INDEX "IDX_INSTANCE_CHANGE_LASTTIME"
ON "INSTANCE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSTANCE_IP"
ON "INSTANCE" ("IP" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Uniques structure for table INSTANCE
-- ----------------------------
ALTER TABLE "INSTANCE" ADD UNIQUE ("APP_ID", "CLUSTER_NAME", "DATA_CENTER", "IP");

-- ----------------------------
-- Checks structure for table INSTANCE
-- ----------------------------
ALTER TABLE "INSTANCE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "INSTANCE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "INSTANCE" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "INSTANCE" ADD CHECK ("DATA_CENTER" IS NOT NULL);
ALTER TABLE "INSTANCE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "INSTANCE" ADD CHECK ("IP" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table INSTANCE
-- ----------------------------
ALTER TABLE "INSTANCE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table INSTANCE_CONFIG
-- ----------------------------
CREATE INDEX "IDX_INSCONFIG_CHANGE_LASTTIME"
ON "INSTANCE_CONFIG" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSCONFIG_CLUSTER_NAME"
ON "INSTANCE_CONFIG" ("CONFIG_CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSCONFIG_CONFIG_APP_ID"
ON "INSTANCE_CONFIG" ("CONFIG_APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSCONFIG_NAMESPACE_NAME"
ON "INSTANCE_CONFIG" ("CONFIG_NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_INSCONFIG_RELEASE_KEY"
ON "INSTANCE_CONFIG" ("RELEASE_KEY" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Uniques structure for table INSTANCE_CONFIG
-- ----------------------------
ALTER TABLE "INSTANCE_CONFIG" ADD UNIQUE ("INSTANCE_ID", "CONFIG_APP_ID", "CONFIG_NAMESPACE_NAME");

-- ----------------------------
-- Checks structure for table INSTANCE_CONFIG
-- ----------------------------
ALTER TABLE "INSTANCE_CONFIG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "INSTANCE_CONFIG" ADD CHECK ("CONFIG_APP_ID" IS NOT NULL);
ALTER TABLE "INSTANCE_CONFIG" ADD CHECK ("CONFIG_CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "INSTANCE_CONFIG" ADD CHECK ("CONFIG_NAMESPACE_NAME" IS NOT NULL);
ALTER TABLE "INSTANCE_CONFIG" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "INSTANCE_CONFIG" ADD CHECK ("RELEASE_DELIVERY_TIME" IS NOT NULL);
ALTER TABLE "INSTANCE_CONFIG" ADD CHECK ("RELEASE_KEY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table INSTANCE_CONFIG
-- ----------------------------
ALTER TABLE "INSTANCE_CONFIG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table ITEM
-- ----------------------------
CREATE INDEX "IDX_ITEM_CHANGE_LASTTIME"
ON "ITEM" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ITEM_NAMESPACE_ID"
ON "ITEM" ("NAMESPACE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ITEM
-- ----------------------------
ALTER TABLE "ITEM" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "ITEM" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "ITEM" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "ITEM" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "ITEM" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "ITEM" ADD CHECK ("ITEM_KEY" IS NOT NULL);
ALTER TABLE "ITEM" ADD CHECK ("NAMESPACE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ITEM
-- ----------------------------
ALTER TABLE "ITEM" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table NAMESPACE
-- ----------------------------
CREATE INDEX "IDX_NAMESPACE_APP_ID"
ON "NAMESPACE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_NAMESPACE_CHANGE_LASTTIME"
ON "NAMESPACE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_NAMESPACE_CLUSTER_NAME"
ON "NAMESPACE" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_NAMESPACE_NAMESPACE_NAME"
ON "NAMESPACE" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table NAMESPACE
-- ----------------------------
ALTER TABLE "NAMESPACE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "NAMESPACE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "NAMESPACE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "NAMESPACE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "NAMESPACE" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "NAMESPACE" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table NAMESPACE
-- ----------------------------
ALTER TABLE "NAMESPACE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table NAMESPACE_LOCK
-- ----------------------------
CREATE INDEX "IDX_NAMESPLOCK_CHANGE_LASTTIME"
ON "NAMESPACE_LOCK" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Uniques structure for table NAMESPACE_LOCK
-- ----------------------------
ALTER TABLE "NAMESPACE_LOCK" ADD UNIQUE ("NAMESPACE_ID");

-- ----------------------------
-- Checks structure for table NAMESPACE_LOCK
-- ----------------------------
ALTER TABLE "NAMESPACE_LOCK" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "NAMESPACE_LOCK" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "NAMESPACE_LOCK" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "NAMESPACE_LOCK" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "NAMESPACE_LOCK" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table NAMESPACE_LOCK
-- ----------------------------
ALTER TABLE "NAMESPACE_LOCK" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PERMISSION
-- ----------------------------
CREATE INDEX "IDX_PERM_CHANGE_LASTTIME"
ON "PERMISSION" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_PERM_PERMISSION_TYPE"
ON "PERMISSION" ("PERMISSION_TYPE" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_PERM_TARGET_ID"
ON "PERMISSION" ("TARGET_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PERMISSION
-- ----------------------------
ALTER TABLE "PERMISSION" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PERMISSION" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PERMISSION" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PERMISSION" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PERMISSION" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PERMISSION" ADD CHECK ("PERMISSION_TYPE" IS NOT NULL);
ALTER TABLE "PERMISSION" ADD CHECK ("TARGET_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PERMISSION
-- ----------------------------
ALTER TABLE "PERMISSION" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_APP
-- ----------------------------
CREATE INDEX "IDX_POAPP_APP_ID"
ON "PORTAL_APP" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POAPP_DATACHANGE_LASTTIME"
ON "PORTAL_APP" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POAPP_NAME"
ON "PORTAL_APP" ("NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_APP
-- ----------------------------
ALTER TABLE "PORTAL_APP" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("ORG_ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("ORG_NAME" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("OWNER_EMAIL" IS NOT NULL);
ALTER TABLE "PORTAL_APP" ADD CHECK ("OWNER_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_APP
-- ----------------------------
ALTER TABLE "PORTAL_APP" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_APP_NAMESPACE
-- ----------------------------
CREATE INDEX "IDX_POAPPNASP_CHANGE_LASTTIME"
ON "PORTAL_APP_NAMESPACE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POAPP_NAMESPACE_APP_ID"
ON "PORTAL_APP_NAMESPACE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POAPP_NAMESPACE_NAME"
ON "PORTAL_APP_NAMESPACE" ("NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_APP_NAMESPACE
-- ----------------------------
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("FORMAT" IS NOT NULL);
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD CHECK ("NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_APP_NAMESPACE
-- ----------------------------
ALTER TABLE "PORTAL_APP_NAMESPACE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PORTAL_SERVER_CONFIG
-- ----------------------------
CREATE INDEX "IDX_POSERCONFIG_CHALASTTIME"
ON "PORTAL_SERVER_CONFIG" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POSERCONFIG_CONFIG_KEY"
ON "PORTAL_SERVER_CONFIG" ("CONFIG_KEY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_POSERCONFIG_CONFIG_VALUE"
ON "PORTAL_SERVER_CONFIG" ("CONFIG_VALUE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PORTAL_SERVER_CONFIG
-- ----------------------------
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("CONFIG_COMMENT" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("CONFIG_KEY" IS NOT NULL);
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD CHECK ("CONFIG_VALUE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PORTAL_SERVER_CONFIG
-- ----------------------------
ALTER TABLE "PORTAL_SERVER_CONFIG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PRIVILEGE
-- ----------------------------
CREATE INDEX "IDX_PRIVILEGE_CHANGE_LASTTIME"
ON "PRIVILEGE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_PRIVILEGE_NAMESPACE_ID"
ON "PRIVILEGE" ("NAMESPACE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PRIVILEGE
-- ----------------------------
ALTER TABLE "PRIVILEGE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "PRIVILEGE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "PRIVILEGE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "PRIVILEGE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "PRIVILEGE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "PRIVILEGE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "PRIVILEGE" ADD CHECK ("PRIVIL_TYPE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PRIVILEGE
-- ----------------------------
ALTER TABLE "PRIVILEGE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table RELEASE
-- ----------------------------
CREATE INDEX "IDX_RELEASE_APP_ID"
ON "RELEASE" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASE_CHANGE_LASTTIME"
ON "RELEASE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASE_CLUSTER_NAME"
ON "RELEASE" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASE_NAMESPACE_NAME"
ON "RELEASE" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASE_RELEASE_KEY"
ON "RELEASE" ("RELEASE_KEY" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RELEASE
-- ----------------------------
ALTER TABLE "RELEASE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("COMMENT_MSG" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("CONFIGURATIONS" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);
ALTER TABLE "RELEASE" ADD CHECK ("RELEASE_KEY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RELEASE
-- ----------------------------
ALTER TABLE "RELEASE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table RELEASE_HISTORY
-- ----------------------------
CREATE INDEX "IDX_RELEASEHI_APP_ID"
ON "RELEASE_HISTORY" ("APP_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_BRANCH_NAME"
ON "RELEASE_HISTORY" ("BRANCH_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_CHANGE_LASTTIME"
ON "RELEASE_HISTORY" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_CLUSTER_NAME"
ON "RELEASE_HISTORY" ("CLUSTER_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_NAMESPACE_NAME"
ON "RELEASE_HISTORY" ("NAMESPACE_NAME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEHI_RELEASE_ID"
ON "RELEASE_HISTORY" ("RELEASE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RELEASE_HISTORY
-- ----------------------------
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("APP_ID" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("BRANCH_NAME" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("CLUSTER_NAME" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("NAMESPACE_NAME" IS NOT NULL);
ALTER TABLE "RELEASE_HISTORY" ADD CHECK ("OPERATION_CONTEXT" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RELEASE_HISTORY
-- ----------------------------
ALTER TABLE "RELEASE_HISTORY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table RELEASE_MESSAGE
-- ----------------------------
CREATE INDEX "IDX_RELEASEMES_CHANGE_LASTTIME"
ON "RELEASE_MESSAGE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_RELEASEMES_MESSAGE"
ON "RELEASE_MESSAGE" ("MESSAGE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table RELEASE_MESSAGE
-- ----------------------------
ALTER TABLE "RELEASE_MESSAGE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "RELEASE_MESSAGE" ADD CHECK ("MESSAGE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table RELEASE_MESSAGE
-- ----------------------------
ALTER TABLE "RELEASE_MESSAGE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table ROLE
-- ----------------------------
CREATE INDEX "IDX_ROLE_CHANGE_LASTTIME"
ON "ROLE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ROLE_ROLE_NAME"
ON "ROLE" ("ROLE_NAME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ROLE
-- ----------------------------
ALTER TABLE "ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "ROLE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "ROLE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "ROLE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "ROLE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "ROLE" ADD CHECK ("ROLE_NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ROLE
-- ----------------------------
ALTER TABLE "ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table ROLE_PERMISSION
-- ----------------------------
CREATE INDEX "IDX_ROLEPERM_CHANGE_LASTTIME"
ON "ROLE_PERMISSION" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ROLEPERM_PERMISSION_ID"
ON "ROLE_PERMISSION" ("PERMISSION_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_ROLEPERM_ROLE_ID"
ON "ROLE_PERMISSION" ("ROLE_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "ROLE_PERMISSION" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "ROLE_PERMISSION" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "ROLE_PERMISSION" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "ROLE_PERMISSION" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "ROLE_PERMISSION" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "ROLE_PERMISSION" ADD CHECK ("PERMISSION_ID" IS NOT NULL);
ALTER TABLE "ROLE_PERMISSION" ADD CHECK ("ROLE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "ROLE_PERMISSION" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table SERVER_CONFIG
-- ----------------------------
CREATE INDEX "IDX_SERCONFIG_CHANGE_LASTTIME"
ON "SERVER_CONFIG" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_SERCONFIG_CONFIG_KEY"
ON "SERVER_CONFIG" ("CONFIG_KEY" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_SERCONFIG_CONFIG_VALUE"
ON "SERVER_CONFIG" ("CONFIG_VALUE" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table SERVER_CONFIG
-- ----------------------------
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("CLUSTER_ADDRESS" IS NOT NULL);
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("CONFIG_COMMENT" IS NOT NULL);
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("CONFIG_KEY" IS NOT NULL);
ALTER TABLE "SERVER_CONFIG" ADD CHECK ("CONFIG_VALUE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SERVER_CONFIG
-- ----------------------------
ALTER TABLE "SERVER_CONFIG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table USER_ROLE
-- ----------------------------
CREATE INDEX "IDX_USERROLE_CHANGE_LASTTIME"
ON "USER_ROLE" ("DATACHANGE_LASTTIME" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_USERROLE_ROLE_ID"
ON "USER_ROLE" ("ROLE_ID" ASC)
LOGGING
VISIBLE;
CREATE INDEX "IDX_USERROLE_USER_ID"
ON "USER_ROLE" ("USER_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table USER_ROLE
-- ----------------------------
ALTER TABLE "USER_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "USER_ROLE" ADD CHECK ("DATACHANGE_CREATEDBY" IS NOT NULL);
ALTER TABLE "USER_ROLE" ADD CHECK ("DATACHANGE_CREATEDTIME" IS NOT NULL);
ALTER TABLE "USER_ROLE" ADD CHECK ("DATACHANGE_LASTMODIFIEDBY" IS NOT NULL);
ALTER TABLE "USER_ROLE" ADD CHECK ("DATACHANGE_LASTTIME" IS NOT NULL);
ALTER TABLE "USER_ROLE" ADD CHECK ("ROLE_ID" IS NOT NULL);
ALTER TABLE "USER_ROLE" ADD CHECK ("USER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table USER_ROLE
-- ----------------------------
ALTER TABLE "USER_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table USERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "USERS" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "USERS" ADD CHECK ("EMAIL" IS NOT NULL);
ALTER TABLE "USERS" ADD CHECK ("ENABLED" IS NOT NULL);
ALTER TABLE "USERS" ADD CHECK ("PASSWORD" IS NOT NULL);
ALTER TABLE "USERS" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "USERS" ADD PRIMARY KEY ("ID");
