spring:
  application:
    name: apollo-portal
  profiles:
    active: github,auth,dev
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 192 # limit query plan cache max size
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tpmall
    url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
    username: tpmall

server:
  port: 8070
  compression:
    enabled: true
  tomcat:
    use-relative-redirects: true

logging:
  file: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP


